-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 15:40:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CARS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `MODEL` VARCHAR(45) NOT NULL,
  `MAX_WEIGHT` DOUBLE NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROADS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROADS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DAILY_CAPACITY` DOUBLE NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CROSSROADS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CROSSROADS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CROSSROAD_ROADS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CROSSROAD_ROADS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CROSSROAD_ID` INT UNSIGNED NOT NULL,
  `ROAD_ID` INT UNSIGNED NOT NULL,
  `DIRECTION` VARCHAR(45) NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`ID`, `CROSSROAD_ID`, `ROAD_ID`),
  INDEX `fk_COUNTRIES_has_CUSTOMS_AREAS_CUSTOMS_AREAS1_idx` (`ROAD_ID` ASC),
  INDEX `fk_COUNTRIES_has_CUSTOMS_AREAS_COUNTRIES_idx` (`CROSSROAD_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_COUNTRIES_has_CUSTOMS_AREAS_COUNTRIES`
    FOREIGN KEY (`CROSSROAD_ID`)
    REFERENCES `mydb`.`CROSSROADS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COUNTRIES_has_CUSTOMS_AREAS_CUSTOMS_AREAS1`
    FOREIGN KEY (`ROAD_ID`)
    REFERENCES `mydb`.`ROADS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
